"""
Django settings for catalog project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# uygulamayla ilgili belli ayarlar ve belli değişkenler sunuyor örn basedir root klasörünün konumunu bize verir

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o)u2ozuci%y-u6_6-w($it6r!19v8oqy9k!@61)#e#_bg)q20)'
# güvenlik anahtarı

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# uygulamanın gelişme aşamasında olduğunu söylüyor

ALLOWED_HOSTS = []


# Application definition

# uygulama içerisinde kurulmuş olan bir admin paneli var ya da login kullanıcı oluşturma
# gibi işlemleri yöneticek olan uygulamalar önceden eklenmiş
INSTALLED_APPS = [
    "pages",
    "movies",
    # "pages.apps.PagesConfig", 26.7 de iptal ettik üstteki kısayol
    # kendi eklediğimiz bir uygulamayi projenin bir parçası yapmış olduk
    'django.contrib.admin',
# ders 26.8 zaten bir admin kullanıcı vs uygulaması var hazır
# hazır olarak gelen tabloları yönetmemizi sağlıyor uyg içerisine ekleyeceğimiz modeller tabloya karşılık geliyor
# bunları admin paneline ekliyoz vs
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # bu zaten varmış ama 26.5 te eklememiz lazımdı
    'django.contrib.humanize' # ders 26.11 tarih şeyi için ekledik
]

# bazı kütüphaneler dahil edilmiş
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# url yapısının yolu burda verilmiş
ROOT_URLCONF = 'catalog.urls'

import os # alttaki için ekledik
# templates için kullanacak olduğumuz ayarlar burda 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
 #root yani basedır ile templates i birleştirecek ve bize bir templates yolu hazırlicak bu path de template imizin konumu olmuş olucak
 # yani gelip şu konumdaki template dosyasındaki index html dosyasını kullan dicez
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'catalog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# database ayarı default olarak sqlite üzerine kurulmuş 
# mysql vs kullanmak istiyorsan değiştirmen gerekiyor
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# yani password un kontrol yapısı doğruluğu nasıl olucak bunları burda belirtebiliyoruz
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'tr' # dili değiştirebiliriz tr dersen türkçe olur
# 26.8 admin paneli dersinde yaptık
TIME_ZONE = 'UTC' # hangi zaman birimini kullandığımız

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# uygulamadaki resim dosyalarımız css js dosyalarımızın konumu ile alakalı bir bilgi
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
